[workspace]
members = [
    "pure-audio",
    "pure-audio/src/macros",
    "pure-audio-clap",
    "pure-audio-wasm",
    "examples/freeverb",
    "examples/gain", 
    "examples/oscillator",
    "examples/pan",
    "examples/surge-synth-saw-demo",
    "examples/tremolo",
    "examples/midi-file-parser",
]
resolver = "2"
