[package]
name = "freeverb"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pure-audio = { path = "../../pure-audio" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
pure-audio-wasm = { path = "../../pure-audio-wasm"}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pure-audio-clap = { path = "../../pure-audio-clap"}
