name: Build

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build workspace
              run: cargo build

            - name: Run tests
              run: cargo test

            - uses: cargo-bins/cargo-binstall@main

            - name: Install wasm32-unknown-unknown build target
              run: rustup target add wasm32-unknown-unknown

            - name: Install wasm-bindgen-cli
              run: cargo binstall wasm-bindgen-cli@0.2.100 --no-confirm

            - name: Build midi-file-parser
              working-directory: examples/webdemo/midi-file-parser
              run: |
                cargo build --target wasm32-unknown-unknown --release
                wasm-bindgen ../../../target/wasm32-unknown-unknown/release/midi_file_parser.wasm --target web --out-dir ../src/assets/midi-file-parser

            - name: Build freeverb example
              working-directory: examples/freeverb
              run: |
                cargo build --target wasm32-unknown-unknown --release
                wasm-bindgen ../../target/wasm32-unknown-unknown/release/freeverb.wasm --target web --out-dir ../webdemo/src/assets/freeverb

            - name: Build oscillator example
              working-directory: examples/oscillator
              run: |
                cargo build --target wasm32-unknown-unknown --release
                wasm-bindgen ../../target/wasm32-unknown-unknown/release/oscillator.wasm --target web --out-dir ../webdemo/src/assets/oscillator

            - name: Build surge-synth-saw-demo example
              working-directory: examples/surge-synth-saw-demo
              run: |
                cargo build --target wasm32-unknown-unknown --release
                wasm-bindgen ../../target/wasm32-unknown-unknown/release/surge_synth_saw_demo.wasm --target web --out-dir ../webdemo/src/assets/surge-synth-saw-demo
            
            - name: Build webdemo
              run: npm install && npm run build
              working-directory: examples/webdemo

            - uses: actions/upload-artifact@main
              with:
                name: dist
                path: examples/webdemo/dist
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: 
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}
        permissions:
            contents: read
            pages: write
            id-token: write
        steps:
            - uses: actions/download-artifact@main
              with:
                name: dist
                path: .
            - uses: actions/configure-pages@main
            - uses: actions/upload-pages-artifact@main
              with:
                path: .
            - id: deployment
              uses: actions/deploy-pages@main